name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build and push image to quay
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: prowlarr
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Dockerfile
      
    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2.7
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/bizalu
        username: ${{ secrets.QUAY_ID }}
        password: ${{ secrets.QUAY_PASSWD }}

    - name: Print image info
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
